import feedparser
NewsFeed = feedparser.parse("https://f95zone.to/forums/-/index.rss")
entry = NewsFeed.entries[1]

print(entry.keys())
print("1")
print(entry.title)
print("2")
print(entry.title_detail)
print("3")
print(entry.published)
print("4")
print(entry.published_parsed)
print("5")
print(entry.links)
print("6")
print(entry.link)
print("7")
print(entry.id)
print("8")
print(entry.guidislink)
print("9")
print(entry.authors)
print("10")
print(entry.author)
print("11")
print(entry.author_detail)
print("12")
print(entry.tags)
print("13")
print(entry.content)
print("14")
print(entry.summary)
print("15")
print(entry.slash_comments)